version: '3'
    
services:
  laundroxpress-db:
    image: postgres
    env_file:
      - ./docker-compose-vars.env
    ports:
      - "5444:5432"
    volumes:
      - postgres-laundroxpress-vol:/var/lib/postgressql/data
  laundroxpress-app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./docker-compose-vars.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - laundroxpress-db
volumes: 
  postgres-laundroxpress-vol:
