# Generated by Django 2.2.16 on 2020-10-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCustomUser', '0003_auto_20201014_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
