# Generated by Django 2.2.16 on 2020-10-14 05:17

from django.db import migrations, models
import laundro.models
import laundro.vallidators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=60, unique=True)),
                ('desciption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to=laundro.models.get_service_image_upload_path, validators=[laundro.vallidators.validate_image_file_extension])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
