# Generated by Django 2.2.16 on 2020-10-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundro', '0001_create_Service_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
