# Generated by Django 2.2.16 on 2020-11-12 09:51

from django.db import migrations, models
import django.db.models.deletion
import laundro.models
import laundro.vallidators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('laundro', '0002_rename_Service_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to=laundro.models.get_service_image_upload_path, validators=[laundro.vallidators.validate_image_file_extension])),
                ('desciption', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='laundro.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
