# Generated by Django 2.2.16 on 2020-11-12 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laundro', '0003_create_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('total_cost', models.FloatField()),
                ('outstanding', models.FloatField()),
                ('status', models.CharField(choices=[('rcv', 'Recieved'), ('inp', 'In Progress'), ('com', 'Completed')], default='rcv', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
